name: scraper

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: deploy-scraper
    env:
      DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
      - name: 💾 Checkout code
        uses: actions/checkout@v4

      - name: 📦 Setup bun
        uses: oven-sh/setup-bun@v2

      - name: 📦 Install dependencies
        run: bun install

      - name: 📦 Install Doppler CLI
        uses: dopplerhq/cli-action@v3

      - name: 🔑 Sync secrets with Cloudflare Worker
        run: doppler secrets --json | jq -c 'with_entries(.value = .value.computed)' | bunx wrangler secret bulk

      - name: 🚀 Deploy to Cloudflare Workers
        run: bun run deploy
